services:
  - type: web
    name: receipt-automation
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /docs   # FastAPI auto-generates Swagger docs at /docs
    envSpecificPreview:
      enabled: true
