services:
  - type: web
    name: receipt-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: receipt-frontend
    env: python
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0



